### PR TITLE
Add Bulgaria

### PR DESCRIPTION
**Pull request by gregn610**
refs #

For information, read and make sure you're okay with the [CONTRIBUTING document](https://github.com/novafloss/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars).

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Docstrings for the Calendar class and specific methods.
- [ ] Calendar country / label added to the README.rst file,
- [ ] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)"

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Changelog amended with a mention describing your changes.

### CODE REVIEW

**Comment by brunobord** [comment]
could you please rebase your branch from upstream, to clean it up ad such?
There are a lot of "howtos" online ; but if you need help to do so, I'd be glad to.

**Comment by gregn610** [comment]
I think I've made a mess of rebasing
~~~
(venv) kochanski:workalendar gregn$ git status
On branch bulgaria
Your branch is up-to-date with 'origin/bulgaria'.
nothing to commit, working directory clean
(venv) kochanski:workalendar gregn$ git fetch novafloss
(venv) kochanski:workalendar gregn$ git rebase novafloss/master
First, rewinding head to replay your work on top of it...
Applying: Add Bulgaria
(venv) kochanski:workalendar gregn$
~~~

**Comment by brunobord** [comment]
can you paste the output of the following command?

```
git diff master
```

**Comment by gregn610** [comment]
It looks like it's just the Bulgaria patch
~~~
$ git diff master
diff --git a/CHANGELOG b/CHANGELOG
index 024fc83..10d71ce 100644
--- a/CHANGELOG
+++ b/CHANGELOG
@@ -6,7 +6,8 @@ master (unreleased)

 - Add Ireland. thx @gregn610 (#152).
 - Bugfix: New Year's Eve is not a holiday in Netherlands (#154).
-- Add Austria. thx @gregn610 (#153)
+- Add Austria.  thx @gregn610 (#153)
+- Add Bulgaria. thx @gregn610 (#156)


 0.8.1 (2016-11-08)
diff --git a/README.rst b/README.rst
index 9fbd465..fca1a82 100644
--- a/README.rst
+++ b/README.rst
@@ -76,6 +76,7 @@ Europe

 * Austria
 * Belgium
+* Bulgaria
 * Czech Republic
 * Denmark
 * Estonia
diff --git a/workalendar/europe/__init__.py b/workalendar/europe/__init__.py
index 79b47cc..d27320d 100644
--- a/workalendar/europe/__init__.py
+++ b/workalendar/europe/__init__.py
@@ -1,6 +1,7 @@
 # -*- coding: utf-8 -*-
 from .austria import Austria
 from .belgium import Belgium
+from .bulgaria import Bulgaria
 from .czech_republic import CzechRepublic
 from .estonia import Estonia
 from .european_central_bank import EuropeanCentralBank
@@ -36,6 +37,7 @@ from .germany import (
 __all__ = (
     Austria,
     Belgium,
+    Bulgaria,
     Catalonia,
     CzechRepublic,
     Denmark,
diff --git a/workalendar/europe/bulgaria.py b/workalendar/europe/bulgaria.py
new file mode 100644
index 0000000..bb53a84
--- /dev/null
+++ b/workalendar/europe/bulgaria.py
@@ -0,0 +1,28 @@
+# -*- coding: utf-8 -*-
+from workalendar.core import WesternCalendar, ChristianMixin
+
+
+class Bulgaria(WesternCalendar, ChristianMixin):
+    "Bulgaria"
+
+    FIXED_HOLIDAYS = WesternCalendar.FIXED_HOLIDAYS + (
+        (3, 3, "Liberation Day"),  # Ден на Освобождението на Б
+        (5, 1, "International Workers' Day"),  # Ден на труда и на междунар
+        (5, 6, "Saint George's Day"),  # Гергьовден, ден на храброс
+        (5, 24, "Saints Cyril & Methodius Day"),  # Ден на българската просвет
+        (9, 6, "Unification Day"),  # Ден на Съединението
+        (9, 22, "Independence Day"),  # Ден на независимостта на Б
+        # wikipedia says Non-attendance day for schools, otherwise a working da
+        # (11, 1, "National Awakening Day"),  # Ден на народните будители
+
+    )
+
+    include_easter_sunday = True
+    include_easter_monday = True
+    include_christmas_eve = True  # Бъдни вечер
+    include_christmas = True  # Рождество Христово
+    include_boxing_day = True
+
+    # wikipedia says The Bulgarians have two days of Christmas,
+    # both called Christmas Day
+    boxing_day_label = "Christmas"
diff --git a/workalendar/tests/test_europe.py b/workalendar/tests/test_europe.py
index d6eafc9..9a81de5 100644
--- a/workalendar/tests/test_europe.py
+++ b/workalendar/tests/test_europe.py
@@ -1,6 +1,7 @@
 # coding=utf-8
 from datetime import date
 from workalendar.europe import Austria
+from workalendar.europe import Bulgaria
 from workalendar.tests import GenericCalendarTest
 from workalendar.europe import CzechRepublic
 from workalendar.europe import Denmark
@@ -54,6 +55,27 @@ class AustriaTest(GenericCalendarTest):
         self.assertIn(date(2016, 12, 26), holidays)  # St Stephens


+class BulgariaTest(GenericCalendarTest):
+    cal_class = Bulgaria
+
+    def test_year_2016(self):
+        holidays = self.cal.holidays_set(2016)
+        self.assertIn(date(2016,  1,  1), holidays)   # New Year's Day
+        self.assertIn(date(2016,  3,  3), holidays)   # Liberation Day
+        self.assertIn(date(2016,  3, 27), holidays)   # Easter Sun
+        self.assertIn(date(2016,  3, 28), holidays)   # Easter Mon
+        self.assertIn(date(2016,  5,  1), holidays)   # International Workers'
+        self.assertIn(date(2016,  5,  6), holidays)   # St George's Day
+        self.assertIn(date(2016,  5, 24), holidays)   # St Cyril & Methodius
+        self.assertIn(date(2016,  9,  6), holidays)   # Unification Day
+        self.assertIn(date(2016,  9, 22), holidays)   # Independence Day
+        self.assertIn(date(2016, 12, 24), holidays)   # Christmas Eve
+        self.assertIn(date(2016, 12, 25), holidays)   # Christmas 1
+        self.assertIn(date(2016, 12, 26), holidays)   # Christmas 2
+        # Non-attendance day for schools, otherwise a working day.
+        self.assertNotIn(date(2016, 11,  1), holidays)   # National Awakening
+
+
 class CzechRepublicTest(GenericCalendarTest):
     cal_class = CzechRepublic
~~~

**Comment by brunobord** [comment]
right, so it looks pretty messy, I see your "add Bulgaria" at least twice.
We've got two solutions here: either I'm taking your branch(es) over and try to tidy-them up, rebase your contribution properly. Fast, but you won't learn how to make clean PRs.

Or the other solution is to wait for me to have time to write a tiny gist on:

* how to maintain an "upstream branch" from novafloss/workalendar and keep it up-to-date,
* how to fork from this upstream and make your pull-requests as minimal as possible.

it'll be better, because you could earn the "happy contributor badge", but will take more time ; time I'm not sure I can have until january (daily work + holidays).

What do you think?

**Comment by gregn610** [comment]
Ok thanks, take them over and make it work please.

**Comment by brunobord** [comment]
as you wanted, I've merged your contribution. thank you very much for your work, much appreciated.

You may want to read the Github help about keeping an upstream fork, that might help a lot for your next pull-requests, on this project or another.

https://help.github.com/articles/syncing-a-fork/

Now, onto the next one :)

**Comment by brunobord** [comment]
BTW, Github has released a UI to handle (simple) conflict resolution from the github.com front-end: https://github.com/blog/2293-resolve-simple-merge-conflicts-on-github

**Pull request closed without merging**
