### PR TITLE
Move workalendar to novafloss

### PR DESCRIPTION
**Pull request by brunobord**
Transfer this repository to the dedicated FLOSS software organization

### CODE REVIEW

**Comment by Natim** [comment]
What bit is missing to merge this?

**Comment by Natim** [comment]
Apparently the github repository is still on the new one.
You should also delete the old one from travis and add the new one (remove also the github hook)

**Comment by brunobord** [comment]
@natim

> What bit is missing to merge this?

I'm waiting for the other incoming PR to be merged, in order to solve the CHANGELOG conflicts at the end.

> Apparently the github repository is still on the new one.

what?

**Comment by Natim** [comment]
I wanted to say that apparently the github already moved to novafloss.

**Comment by brunobord** [comment]
yeah, sure, I did the migration and this PR is just acknowledging it in the changelog, readme, etc.

**Pull request merged**
