### PR TITLE
Moved all the american countries in their own module

### PR DESCRIPTION
**Pull request by brunobord**

### CODE REVIEW

**Comment by Natim** [comment]
You might want to split the tests as well.

**Comment by brunobord** [comment]
> You might want to split the tests as well.

Ah you're right

**Comment by brunobord** [comment]
well, we didn't do it after the "Europe" split... I wonder if it's necessary for this one... except that I'm expecting a "test_brazil.py" module pretty soon (ref: #187)

**Comment by Natim** [comment]
That was an idea but i you feel it is not needed you can ignore my comment.

**Pull request merged**
