### PR TITLE
Remove the status telling the lib is beta.

### PR DESCRIPTION
**Pull request by Natim**
refs #161 

- [x] lib is not beta anymore,
- [ ] change and refresh ``setup.py`` classifiers
- [ ] prepare for 1.0.0, which will be the next release

### CODE REVIEW

**Comment by brunobord** [comment]
maybe we could rework on the ``setup.py`` classifiers also? telling that this lib is Production Ready?

**Comment by ewjoachim** [comment]
You could also make it 1.0.0

**Comment by brunobord** [comment]
@ewjoachim +1

**Comment by ewjoachim** [comment]
Well , the ticket is closed but the code isn't merged yet.

**Comment by brunobord** [comment]
so I'm taking this over

**Comment by brunobord** [comment]
closed by #166

**Pull request closed without merging**
