### PR TITLE
added medthod to get holiday label from date #120

### PR DESCRIPTION
**Pull request by JanMalte**

### CODE REVIEW

**Comment by brunobord** [comment]
Looks great. could you please rebase from master in this branch in order to get the travis build status available? many thanks.

**Comment by brunobord** [comment]
oh, and while you're at it, could you please amend the changelog?

**Comment by JanMalte** [comment]
Ok, should be ready to merge

**Comment by brunobord** [comment]
conflicting CHANGELOG, please rebase (sorry about that, can't find a way to prevent these ugly changelog conflicts).

**Comment by brunobord** [comment]
manually merged locally. thank you for this.

**Pull request closed without merging**
